import type { BlockDef, GitFramework } from "@thunder/types";

export type RendererTarget = "astro" | "react";

export interface GeneratedRenderer {
  target: RendererTarget;
  /** Suggested repo path for the file. */
  path: string;
  /** File contents. */
  code: string;
  language: "tsx" | "astro";
}

export function rendererTargetForFramework(framework: GitFramework | null | undefined): RendererTarget {
  return framework === "astro" ? "astro" : "react";
}

/** PascalCase identifier safe for use as a component name. */
function toComponentName(label: string, key: string): string {
  const base = (label || key).replace(/[^\w\s-]/g, " ");
  const pascal = base
    .split(/[\s_-]+/)
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join("");
  const valid = /^[A-Za-z]/.test(pascal) ? pascal : `Block${pascal}`;
  return valid || "Block";
}

/** Best-effort import specifier from a component's source file. */
function importSpecifier(def: BlockDef): string {
  if (def.source?.kind === "component" && def.source.file) {
    const noExt = def.source.file.replace(/\.(astro|tsx|jsx|ts|js|vue|svelte)$/i, "");
    if (noExt.startsWith("src/")) return `@/${noExt.slice(4)}`;
    return `@/${noExt}`;
  }
  return `@/components/${toComponentName(def.label, def.key)}`;
}

/** Assign a unique component identifier to each block. */
function resolveNames(blocks: BlockDef[]): { def: BlockDef; name: string; spec: string }[] {
  const used = new Set<string>();
  return blocks.map((def) => {
    let name = toComponentName(def.label, def.key);
    while (used.has(name)) name = `${name}_`;
    used.add(name);
    return { def, name, spec: importSpecifier(def) };
  });
}

const BANNER =
  "// Generated by Thunder CMS. Maps a page's blocks[] to your components.\n" +
  "// Adjust the import paths to match your project, then re-export as needed.";

function generateReact(blocks: BlockDef[]): string {
  const entries = resolveNames(blocks);
  const imports = entries.map((e) => `import ${e.name} from "${e.spec}";`).join("\n");
  const mapEntries = entries.map((e) => `  ${JSON.stringify(e.def.key)}: ${e.name},`).join("\n");

  return `${BANNER}
import type { ComponentType } from "react";
${imports}

type Block = { _template: string; [key: string]: unknown };

const BLOCK_COMPONENTS: Record<string, ComponentType<any>> = {
${mapEntries}
};

export function Blocks({ blocks = [] }: { blocks?: Block[] }) {
  return (
    <>
      {blocks.map((block, index) => {
        const Component = BLOCK_COMPONENTS[block._template];
        if (!Component) return null;
        return <Component key={index} {...block} />;
      })}
    </>
  );
}
`;
}

function generateAstro(blocks: BlockDef[]): string {
  const entries = resolveNames(blocks);
  const imports = entries.map((e) => `import ${e.name} from "${e.spec}";`).join("\n");
  const mapEntries = entries.map((e) => `  ${JSON.stringify(e.def.key)}: ${e.name},`).join("\n");

  return `---
${BANNER.replace(/^\/\/ /gm, "// ")}
${imports}

type Block = { _template: string; [key: string]: unknown };

const BLOCK_COMPONENTS: Record<string, any> = {
${mapEntries}
};

const { blocks = [] } = Astro.props as { blocks?: Block[] };
---
{blocks.map((block) => {
  const Component = BLOCK_COMPONENTS[block._template];
  return Component ? <Component {...block} /> : null;
})}
`;
}

// --- Auto-glob generators (folder-driven; new components need no re-wiring) ---

const KEY_FN_TS = `function keyFor(path: string): string {
  const parts = path.split("/");
  let name = parts[parts.length - 1].replace(/\\.(astro|tsx|jsx)$/, "");
  if (name.toLowerCase() === "index") name = parts[parts.length - 2] ?? name;
  return name.charAt(0).toLowerCase() + name.slice(1);
}`;

function generateAstroGlob(componentsRoot: string): string {
  const root = componentsRoot.replace(/\/+$/, "");
  return `---
// Generated by Thunder CMS. Auto-imports every component under ${root}/,
// so a page's blocks[] render with zero extra wiring — add a component, use it.
const modules = import.meta.glob("/${root}/**/*.astro", { eager: true });

${KEY_FN_TS}

const BLOCK_COMPONENTS: Record<string, any> = {};
for (const [path, mod] of Object.entries(modules)) {
  const name = path.split("/").pop() ?? "";
  if (name.replace(/\\.astro$/, "") === "Blocks") continue;
  BLOCK_COMPONENTS[keyFor(path)] = (mod as any).default;
}

const { blocks = [] } = Astro.props as { blocks?: { _template: string }[] };
---
{blocks.map((block) => {
  const Component = BLOCK_COMPONENTS[block._template];
  return Component ? <Component {...block} /> : null;
})}
`;
}

function generateReactGlob(): string {
  // The renderer is written into the components root, so "." is that folder.
  return `${BANNER}
// Auto-imports every component in this folder via webpack's require.context
// (Next.js) — add a component here and it becomes usable with no re-wiring.
import type { ComponentType } from "react";

${KEY_FN_TS}

// eslint-disable-next-line @typescript-eslint/no-explicit-any
const ctx = (require as any).context(".", true, /\\.(tsx|jsx)$/);

const BLOCK_COMPONENTS: Record<string, ComponentType<any>> = {};
for (const filePath of ctx.keys() as string[]) {
  const name = (filePath.split("/").pop() ?? "").replace(/\\.(tsx|jsx)$/, "");
  if (name === "Blocks") continue;
  if (!/^[A-Z]/.test(name) && name.toLowerCase() !== "index") continue;
  const mod = ctx(filePath);
  if (mod && mod.default) BLOCK_COMPONENTS[keyFor(filePath)] = mod.default;
}

type Block = { _template: string; [key: string]: unknown };

export function Blocks({ blocks = [] }: { blocks?: Block[] }) {
  return (
    <>
      {blocks.map((block, index) => {
        const Component = BLOCK_COMPONENTS[block._template];
        if (!Component) return null;
        return <Component key={index} {...block} />;
      })}
    </>
  );
}
`;
}

export interface RendererOptions {
  /** "glob" auto-imports the whole folder; "explicit" lists each block import. */
  mode?: "glob" | "explicit";
  /** Components root (glob mode); the renderer is written here as Blocks.*. */
  componentsRoot?: string;
}

export function generateRenderer(
  framework: GitFramework | null | undefined,
  blocks: BlockDef[],
  opts: RendererOptions = {},
): GeneratedRenderer {
  const target = rendererTargetForFramework(framework);
  const mode = opts.mode ?? "glob";
  const root = (opts.componentsRoot?.replace(/\/+$/, "") || "src/components").trim();

  if (target === "astro") {
    return {
      target,
      path: `${root}/Blocks.astro`,
      code: mode === "glob" ? generateAstroGlob(root) : generateAstro(blocks),
      language: "astro",
    };
  }
  return {
    target,
    path: `${root}/Blocks.tsx`,
    code: mode === "glob" ? generateReactGlob() : generateReact(blocks),
    language: "tsx",
  };
}
